;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Spell.Mod.Obsidian",NewTagName="Spell.Mod.Blindness")
+GameplayTagRedirects=(OldTagName="Spell.Mod.HealOrCalm",NewTagName="Spell.Mod.Calm")
+GameplayTagRedirects=(OldTagName="Spell.Mod.ElectricStun",NewTagName="Spell.Mod.Electric")
+GameplayTagList=(Tag="Spell.Mod.Blindness",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Calm",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Clash",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Durability",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Electric",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Explode",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Heal",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Light",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Loud",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Slow",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Smoke",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.SpeedUp",DevComment="")
+GameplayTagList=(Tag="Spell.Mod.Stun",DevComment="")
+GameplayTagList=(Tag="Spell.Utility.Color",DevComment="")
+GameplayTagList=(Tag="Spell.Utility.Early",DevComment="")
+GameplayTagList=(Tag="Spell.Utility.Sound",DevComment="")
+GameplayTagList=(Tag="Spell.Utility.Visual",DevComment="")

